### ISSUE TITLE
Redmi Note 9t

### ISSUE THREAD

**Issue by welcome-to-semiconductor-hell** [StatiXOS/android_device_xiaomi_cannon#1]
It's rom for Redmi Note 9t, not for Note 9 5G. Redmi note 9 5g have ultra wide camera. Redmi Note 9 5G was announced in November 2020. Redmi Note 9 5G have 4 or 6 or 8 gb of ram. Redmi Note 9T have "cannon" codename

**Comment by welcome-to-semiconductor-hell** [comment]
Sorry for my bad english

**Comment by mvaisakh** [comment]
This device tree is for both Note 9T and Note 9 5G, unified. I have the Redmi Note 9T, and hence the description for it

**Comment by welcome-to-semiconductor-hell** [comment]
Note 9G is using a different modem. This firmware does not work correctly on it. Prove: https://4pda.to/forum/index.php?showtopic=1013059&view=findpost&p=106435873. This is a mirror of the site 4pda.ru. Due to the fact that the domain is blocked, you need to use the mirror 4pda.to. The firmware for these phones differs only in the modem firmware.

**Comment by mvaisakh** [comment]
This device tree does not modify modem in any way. And this rom has not been released yet.
And I say again, this is a unified tree and shall work with both Redmi Note 9T and Note 9 5G.

**Comment by welcome-to-semiconductor-hell** [comment]
OK. Anyway, thanks for developing the custom ROM. If you need to test the firmware, you can use the community 4pda.ru.

**Comment by mvaisakh** [comment]
I'm not Russian, but roms will be released through our [Telegram Channel](http://t.me/StatixOSReleases) or [XDA](https://forum.xda-developers.com/f/redmi-note-9t.12075/), I have no idea about 4PDA.ru
